### PR TITLE
update to the front end

### PR DESCRIPTION
**Pull request by skandelol**
still trying stuff out but getting closer to what I think it should be

### CODE REVIEW

**Comment by ryanmart25** [comment]
Remove logging of sensitive information in cleartext.

**Review by ryanmart25 — CHANGES_REQUESTED** [review]
login.js: Remove lines 15-16, 34. Modify line 11: Remove ableist slur. 
plaintext logging of username and password is a massive security risk. 
For obvious reasons. Review your code before you commit and attempt to merge.

**Comment by skandelol** [comment]
> login.js: Remove lines 15-16, 34. Modify line 11: Remove ableist slur. plaintext logging of username and password is a massive security risk. For obvious reasons. Review your code before you commit and attempt to merge.

user and password are placeholders, they don't need be removed. placeholders until endpoints are done.

**Comment by ryanmart25** [comment]
I recognize they are placeholders. Loggin these placeholders to the console is not necessary. Just remove the two lines.

**Pull request merged**
